### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Martadubugmordor** [xnydl/sb#3]
AAECAZICCOTuA7CKBLWKBImLBKWNBO+kBKWtBISwBAvA7AOvgASwgASJnwSunwTanwTPrAT/vQSn1ATaoQWKugUA

**Comment by xnydl** [comment]
The robot can't understand this card set. I'm too lazy to write it

**Comment by Martadubugmordor** [comment]
也许有Ramp Druid的东西？

**Comment by Martadubugmordor** [comment]
也许有 Ramp Druid 的东西？

**Comment by Martadubugmordor** [comment]
Maybe there is something for Ramp Druid?

**Comment by xnydl** [comment]
If you want to play, you can give advice to the author

**Comment by Martadubugmordor** [comment]
Whatever you want , I thought you had the code for the deck for the bot

**Comment by Lem6o** [comment]
It looks like the bot has stopped seeing or using the Predator card in this profile _77标准(S)娜迦瞎 (NAGA DEMON HUNTER)_

**Comment by xnydl** [comment]
Skin problems

**Comment by xnydl** [comment]
> 机器人似乎已停止查看或使用此配置文件中的 Predator 卡_77标准(S)娜迦瞎 (NAGA DEMON HUNTER)_

**Comment by xnydl** [comment]
Sorry, the policy really doesn't work properly. I've fed back relevant problems with the author
